### ISSUE TITLE
Is it possible to specify chords played in a grand staff?

### ISSUE THREAD

**Issue by rvzzz** [daviddekleer/EasyMIDI#1]
like that: 

![screen shot 2018-03-27 at 04 20 25](https://user-images.githubusercontent.com/3394457/37945046-35e0af3a-3176-11e8-8c07-c3f9e2b38a6f.png)

Thanks! 😄

**Comment by rvzzz** [comment]
got it, just needed to specify a new track with a lower octave. thanks, this package makes it indeed easy.

**Comment by daviddekleer** [comment]
Ok, nice to hear you figured it out :-)
